import Head from 'next/head'
import Link from 'next/link'

import Hero from '../components/Hero'
import CardSection from '../components/CardSection'
import CardUs from '../components/CardUs'

import BanjoImg from '../public/bass_1.jpg'
import AcousticImg from '../public/acoustic_1.jpg'
import ElextricImg from '../public/electric_1.jpg'
import WhyUsImg1 from '../public/whyus_1.png'
import WhyUsImg2 from '../public/whyus_2.png'
import WhyUsImg3 from '../public/whyus_3.png'
import WhyUsImg4 from '../public/whyus_4.png'





export default function Home() {
  return (
    <>
      <Head>
        <title>E-guitar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <section className='lg:flex lg:justify-evenly items-center gap-5 p-10 '>
          <div className='lg:w-1/4 p-10'>
            <h2 className='font-bold text-xl mb-5 text-gray-900'>The Best Guitars For Newcomers to Pro Players</h2>
            <p className='text-gray-700 mb-5'>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
            <Link href="/categories"><button className='btn'>Explore</button></Link>
          </div>
          <CardSection img={BanjoImg} title={'Bass'} price={'500'} />
          <CardSection img={AcousticImg} title={'Acoustic'} price={'200'} />
          <CardSection img={ElextricImg} title={'Electric'} price={'700'} />
        </section>
        <section className='bg-slate-800 p-10'>
          <div className=''>
            <h2 className='font-bold text-3xl mb-5 text-cyan-600'>Why Chose Us</h2>
            <p className='text-gray-300 mb-5'>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
          </div>
          <div className='md:flex justify-evenly'>
            <CardUs img={WhyUsImg1} title={'Free Shipping'} />
            <CardUs img={WhyUsImg2} title={'Easy to Shop'} />
            <CardUs img={WhyUsImg3} title={'24/7 Support'} />
            <CardUs img={WhyUsImg4} title={'Hassle FreeReturns'} />
          </div>
        </section>
        <section className='p-5'>
          <div className='lg:w-1/4 p-10'>
            <h2 className='font-bold text-xl mb-5 text-gray-900'>The Best Guitars For Newcomers to Pro Players</h2>
            <p className='text-gray-700 mb-5'>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
          </div>
        </section>

      </main>
    </>
  )
}
