import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Header from '../components/Header'

import HeroImg from '../public/hero_image.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>E-guitar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className='relative bg-slate-900  w-full h-96 drop-shadow-2xl'>
          <div className='absolute h-full w-full z-10 flex justify-evenly items-center'>
            <h1 className='text-white text-center text-6xl'>E-Guitar</h1>
            <p className='text-white text-2xl'>Music Instruments, Accessories and Equipment</p>
          </div>
          <div className='relative h-[100%] opacity-25'>
            <Image src={HeroImg} alt='Banner Image' objectPosition='center' objectFit='cover' layout='fill' />
          </div>
        </div>
      </main>
    </>
  )
}
