import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>E-guitar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-red-500 text-center uppercase p-10 text-2xl'>Titi me pregunto si tenia mucha novia</h1>
      </main>
    </div>
  )
}
